---
title: "Substation Data Pipelining with GCP"
format: html
execute:
  echo: true
  warning: true
  message: true
jupyter: python3
category: "data Quality Monitoring"
author: "Minkun Kim"
date: "3.22.2026"
categories:
  - data quality monitoring
comments:
  utterances:
    repo: "mainkoon81.github.io/minkun-website/"
---

## Product Requirements Document (PRD)

### [A]. Overview 
#### (1) background
  
The ongoing transition toward a climate-neutral energy system is accelerating the integration of decentralized renewable energy sources - often referred to as sector coupling - such as photovoltaic (PV) systems and wind turbines, along with the electrification of transportation through electric vehicles (EVs). Consequently, as described in Figure 01, current low-voltage (LV) grids are experiencing increasing operational stress due to bi-directional power flows and rising peak demand. In this evolving environment, distribution system operators (DSOs) are tasked with ensuring secure and reliable grid operation. Real-time monitoring of the grid state, combined with accurate assessment of peak load (energy consumption) and peak generation (energy injection), is therefore essential to prevent thermal overloading, mitigate voltage violations, and maintain system stability

![Figure 01. Decentralized energy consumption and generation in low-voltage grids: It leads to bi-directional power flows - power no longer flows uni-directionally from the transformer to consumers -, increasing the risk of overloading and voltage instability. 
](images/powerGrid.png){width="600"}



#### (2) objective
  
Smart secondary substations such as **digiONS** provide real-time feeder cable monitoring, which significantly enhances system observability. However, substation-level monitoring systems with **digiONS**, particularly those based on SCADA infrastructure, are susceptible to `measurement noise`, `incomplete sampling intervals`, `aggregation artifacts`, and `communication failures`. These issues reduce the reliability of the data and make direct analytical use difficult.  Consequently, **systematic data acquisition control and quality assurance mechanisms are indispensable for maintaining the credibility of the LV grid analysis.**

- `Goal`: Our goal is to ensure the quality of data collected during the operation of the smart secondary substations. We design and implement a scalable data pipeline for operational substation monitoring data using a **Medallion architecture** (Bronze → Silver → Gold). The proposed pipeline is designed to:
  - ingest operational measurements from substation monitoring systems
  - perform data quality validation 
  - transform raw data into analysis-ready datasets 
  - provide monitoring dashboards and automated alerting mechanisms.



### [B]. Data: 

The empirical data used in this study are sourced from the publicly available Kaggle dataset: *Power Exchange Data Germany*. The dataset provides detailed operational measurements for one representative substation. The investigated substation supplies a LV grid consisting of 89 households, 450 kW of installed PV capacity, and a battery storage system rated at 300 kW / 850 kWh. The operational dataset collected from this substation contains `active power` measurements recorded at the LV busbar. These measurements are particularly useful for system analysis, as they reflect the combined effects of household demand, photovoltaic generation injected into the grid, and battery operation under bidirectional power flow conditions. In this chapter, these active power measurements serve as the primary basis for investigating data acquisition consistency and quality assurance aspects. 

![Figure 02. Substation-level Active Power measurements and sample counts. 
](images/data02.png){width="800"}

A snapshot of the dataset is shown in Figure 02. Active power value is reported as 15-minute average values (kW), computed from underlying 1-minute measurements. In addition to the average value, the dataset includes the corresponding minimum and maximum 1-minute readings within each aggregation interval, as well as the number of valid samples collected from each 15-minute interval in the SCADA-based aggregation process. However, as discussed earlier, the dataset may contain data quality issues commonly associated with SCADA monitoring systems, such as incomplete sampling intervals, aggregation artifacts, and communication failures. The **Available Data Count** column shown in Figure 02. reflects this aspect by indicating the number of available measurements used in the aggregation of each interval. To examine these data quality issues, this study formulates eight assurance
standards at the level of each 15-minute observation interval:

- **Missing timestamp**: each record is checked for missing Timestamp value, which may arise from communication failures or related disruptions.
- **Missing available data count**: each record is checked for the presence of the Available Data Count value, which may arise from communication failures or related disruptions.
- **Missing signal identifier**: each record is checked for a valid signal identifier so that observations can be uniquely referenced.
- **Duplicate signal identifier**: each record is checked to ensure that no duplicated signal identifier exists, so that observations can be uniquely referenced.
- **Timestamp misalignment**: each Timestamp value is checked to confirm that it falls on a quarter-hour boundary (00, 15, 30, or 45 minutes), as expected for a stable 15-minute signal feed.

In addition to these structural issues, this study also considers consistency-related problems in the reported active power measurement statistics.

- **Invalid minimum-average relationship**: the reported Active Power min value must not exceed the Active Power AVG value, in accordance with the expected ordering of aggregated statistics.
- **Invalid average-maximum relationship**: the reported Active Power AVG value must not exceed the Active Power max value, since such a case would indicate inconsistency in the aggregated statistics.
- **Unexpected sample count**: the aggregation window is checked for completeness by requiring the Available Data Count measurements within each 15-minute interval to equal 15.

Among these, **unexpected sample count** is particularly important, since deviations from this expected count may indicate irregularities in the SCADA-based acquisition process. Taken together, these quality issues provide a practical basis for judging whether a recorded interval is sufficiently reliable for subsequent analysis.


### [C]. KPIs: 

| Metric              | Target             | Criteria                          |   
| ------------------- | -------------------| --------------------------------- | 
| Completeness rate   | ≥ 99%              | NO.valid intervals / 96           | 
| Timestamp Alignment | 96                 | NO.aligned intervals [00 15 30 45]|
| Q-Test Pass Rate    | ≥ 95%              | dbt test result                   |
| E[t] to Acknowledge | ≤ 1 hour           | As of the alert time              | 
| E[t] to Repair      | ≤ 12 hours         | Turnaround time                   | 

(Each day contains 24 × 4 = 96 expected intervals)


### [D]. Functional Requirements 

- **Medallion Layer Implementation**

  - ***Bronze***: Raw CSV data are ingested using Apache Spark (append-only) + metadata (ingestion timestamp, batch identifiers, etc.)
  
  - ***Silver***: Schema standardization (parsing timestamp, normalizing event types, applying conditional column rules, etc.)
    - **validation rules**:
      - `active_power_min` ≤ `active_power_mean` ≤ `active_power_max`
      - `data_count` ≤ 15
      - timestamp continuity check.

  - ***Gold***: Curating data marts designed for analytical use
    - Data Mart for "Load Ratio Analysis"
    - Monitoring Table I. (daily KPI) 
      - | NO.valid intervals | NO.empty intervals | NO.partial intervals | NO.aligned intervals | completeness rate |
    - Monitoring Table II. (daily issue-type summary) 
      - | issue type | issue count | first issue ts | last issue ts |
    - Analytical Table 
      - | signal_id | signal_date | quarter_hour_slot | DataCNT | AVGsig | MINsig | MAXsig |
    - Derived Indicators
      - daily peak load
      - load variability metrics
      - power fluctuation statistics

- **Orchestration (Airflow)**
  - Airflow orchestrates the transformation workflow within the Medallion architecture. 
    - Schedule execution ⇒ Ingestion using Spark ⇒ dbt run(Silver/Gold) ⇒ dbt test ⇒ slack  
    - In case of failure in any transformation or validation, the workflow automatically retries tasks and provides log links for troubleshooting.
    - Data Quality Monitoring (dbt test)
      - not_null, unique, accepted_values, relationships  

- **Alerting (Slack)**
  - Airflow ensures that each transformation stage is executed sequentially and that downstream tasks are only triggered when upstream validation checks succeed.  
    - If DQ-tests fail, automated alerts are sent via Slack notifications. 
    - The alerts include information (batch ID, affected tables, causes of the issue, etc.)
    - Rapid detection and resolution of data quality issues within the pipeline.

- **Scheduling**
  - The transformation workflow is scheduled to execute on a daily basis to ensure that analytical datasets in the Gold layer remain consistent with the latest available operational measurements. Failure handling mechanisms include:
    - automatic retry attempts
    - task dependency validation
    - alert notifications to system operators.




  
### [E]. Non-functional Requirements 

- **SLA** (service level agreement) 
  - Monitoring and reporting must be available daily.
  - Gold Mart tables must be published before 7 am. with the data derived from the previous day's records.
  - If dbt tests fail, the publication of Gold tables is blocked as a gatekeeping mechanism.
- **Performance & Cost**
  - Daily pipeline execution should complete within 30 minutes.
  - Query costs are managed by using Google Cloud BigQuery table partitioning based on the `event_date` field.
- **Safety**
  - Access to Bronze layer raw data should be restricted to authorized users.

  

### [F]. Data Quality Validation Rules

Given that SCADA-based operational datasets are prone to measurement and communication errors, a structured set of data quality rules is implemented in the Silver layer to ensure reliability before the data are exposed for analytical use. The validation rules focus on four main dimensions:
- Completeness, Validity, Consistency, Timeliness

- Data Quality Test Example

| ID  | Table            | Column        | Test type        | Description     |
| --- | ---------------- | ------------- | ---------------- | --------------- |
| T01 | bronze.raw       | timestamp     | unique           | duplicate check |
| T02 | silver.power_Trf | active_power  | not_null & valid | accepted values |
| T03 | silver.power_Trf | data_count    | not_null & valid | accepted values |
| T04 | silver.power_Trf | active_power  | freshness        | update check    |
| T05 | gold.monitoring  | data_count    | completeness     | threshold check |
| T06 | gold.monitoring  | load_ratio    | not_null & valid | accepted values |
| T07 | gold.monitoring  | load_ratio    | freshness        | SLA validation  |

- Data quality monitoring is implemented through automated validation checks executed during pipeline execution.

- If any rule fails:
  - the affected dataset is flagged
  - alerts are generated
  - Gold dataset publication may be temporarily blocked.


### [G]. System Architecture

![Figure 03. ETL data pipeline architecture for substation monitoring simulation. The architecture integrates streaming ingestion (Kafka and Spark), cloud-based landing storage (GCS), Medallion data modeling in BigQuery (Bronze-Silver-Gold), orchestration via Apache Airflow, and automatic visualization and alerting through Looker Studio and Slack. 
](images/architecture.png){width="600"}


### [H]. Stakeholders and Roles

| Role              | In charge      | Responsibility            | 
| ----------------- | -------------- | ------------------------- | 
| Data Product Owner| David Lindburg | Define objectives         | 
| Data Engineer     | Thomas Ward    | Implement pipeline        | 
| Analyst           | Martin Müller  | Use for analysis          | 
| Operations Team   | Ashley Johnson | Respond to alerts/failures| 

### [I]. Reporting and Communication

- **Slack Alerts include:**
  -	pipeline failure notification
  - data quality test failure
  - SLA violations
  
- Example of a Slack notification generated by the pipeline:

::: callout-note
**rotating_light:** Data Freshness SLA Violation

**Dataset:** Calendar Availability
**Batch ID:** 2026-03-07-01
**Affected Table:** gold_calendar_availability

**Issue:**
3% of listings have not updated their calendars for more than 24 hours.

**Impact:**
City-level availability metrics may be incomplete.

**Suggested Action:**
Check upstream ingestion jobs and API synchronization logs.

:::

![Figure 03. Slack Notification. 
](images/medal07.png){width="800"}



- **Daily Monitoring Report includes:**
  - pipeline execution status
  - dataset freshness
  - data quality test results
  - detected anomalies.



### [J]. Continuous Improvement

- The pipeline will be continuously improved through:
  - periodic data quality & SLA compliance review.
  - A built-in review process ensures that data quality rules are validated whenever new tables are added.
  - Adjustment of validation rules.
  - Feedback-driven rule improvement: reducing false positives and improving alert precision
  - Enhancement of monitoring dashboards.
  - Optimization of pipeline performance.


--------------------------------------------------------------------------------
## Implementation+++++++++++++++++++++++++++++

### [A]. Setup 

#### (1) Open with WLS
Assuming that `WSL.Ubuntu-22.04` is used on a local machine running Windows 11, the terminal in VS Code is first opened to prepare remote access to Google Cloud Platform. For SSH-based access, a public-private key pair must be generated using the following command:

::: callout-note
minkun@Benny:~$ ssh-keygen -t rsa -b 4096 -f ~/.ssh/gcp_vm 
:::

Note that the **public key** must later be uploaded to GCP for SSH authentication.

In the directory `/home/minkun/.ssh`, the generated key pair appears as **gcp\_vm** and **gcp\_vm.pub**, where the former denotes the private key and the latter the public key. Bear in mind that the same directory will also later include an SSH `config` file, which enables VS Code to connect to the GCP virtual machine remotely. After the **external IP address** of the GCP instance is assigned, it should be recorded in this `config` file together with the corresponding SSH connection parameters.   

#### (2) Go to GCP
In GCP, what comes first is to create VM instance (compute engine). Assuming the following specification:

::: callout-note
- E2 standard 4 (4CPU + 16GB memory)
- Ubuntu 24.04 LTS Minimal with boot disk size: 100GB
::: 
Next, access the VM instance and open the **SSH terminal** for the initial setup. We then install the necessary commands and software packages (we use docker) that are needed for the project but are not installed by default on the GCP virtual machine.

::: callout-note
minkun_kim4@instance-20260311-173303:~$ sudo apt update -y  
minkun_kim4@instance-20260311-173303:~$ sudo apt install -y git curl unzip  
minkun_kim4@instance-20260311-173303:~$ sudo apt install -y ca-certificates gnupg 
minkun_kim4@instance-20260311-173303:~$ curl -fsSL https://get.docker.com/ | sudo sh  
minkun_kim4@instance-20260311-173303:~$ sudo usermod -aG docker $USER 

minkun_kim4@instance-20260311-173303:~$ newgrp docker 

minkun_kim4@instance-20260311-173303:~$ docker --version  
minkun_kim4@instance-20260311-173303:~$ docker compose version 
::: 
We also need to set the firewall for our VM instance. For this, we need our IP address. Go fetch your IP address from: https://whatismyipaddress.com/ 

Again, access our VM instance, go and find "Network interface", and click "network detail", and go to the firewall on the left. Paste your IP address as well as set the port number on TCP. 

::: callout-note
- Airflow: 8085 
- Spark: 8081 
- Kafka: 8080 
- Dbt: 7999 
::: 
After completing the initial setup, locate the IP address section in the left sidebar of the GCP interface. There, promote the assigned **external IP address** to a **static IP address** and provide a name for it, for example "mk-gcp-instance-ip". The resulting external IP address should be kept safe, as it will later be added to the SSH `config` file for remote access through VS Code.

Register the **public key** generated earlier for SSH access to the GCP virtual machine. To do this, open the VM instance settings again, click Edit, scroll down to the SSH Keys section, and select Add item. Then paste the contents of the public key file into the field and save the changes.-----THE END


#### (3) Go back to your device
Finally, we build a SSH `config` file to register host. 

::: callout-note
Host gcp-de-vm

    - HostName 34.40.116.42 (new external ip)
    - User minkun
    - IdentityFile ~/.ssh/gcp_vm
    - IdentitiesOnly yes
::: 

![Figure 04. See where does the config file locate. 
](images/configggg.png){width="600"}


Since you are a windows user, GO and find `C:\Users\kimmk\.ssh` (windows path) in your laptop, make sure you locate the correct config file too!

Now, using this config file, we can access GCP remotely: from `WLS: Ubuntu-22.04` via (remote tunnel) to `SSH: gcp-de-vm`. Hooooray! Next, in your remote VM environment, create folders and everything:

::: callout-note
minkun@instance-20260311-173303: ~$ mkdir -p 00-network 10-kafka 20-spark 30-airflow 40-dbt 50-apps/data 50-apps/replayer secrets scripts docs 
:::
Plus, add your csv dataset.


### [B]. From Docker to Bronze Medallion

#### (1) Set Docker afloat 
Let us now activate Docker and Docker Compose. For this, the required files are first organized in their respective project directories.

::: callout-note
For **kafka-10**
 - `docker-compose.yml`

For **spark-20**
 - `docker-compose.yml`
 - `Dockerfile`

For **airflow-30**
 - `docker-compose.yml`
 - `.env`

For **airflow-30>.dbt** 
 - `profiles.yml`

For **airflow-30>dags** 
 - `dbt_signal_layered.py`

For **dbt-40**
 - `docker-compose.yml`
 - `Dockerfile`

For **dbt-40>.dbt**
 - `profiles.yml`

For **dbt-40>my_dbt_project**
 - `dbt_project.yml`
 - `packages.yml`
 
For **dbt-40>my_dbt_project>models>bronze**
 - `brz_signal.sql`
 
For **dbt-40>my_dbt_project>models>silver**
 - `slv_signal.sql`
 - `silver.yml`
 
For **dbt-40>my_dbt_project>models>gold**
 - `fct_signal_clean_15min.sql`
 - `fct_signal_issue_daily.sql`
 - `fct_signal_quality_daily.sql`
 - `gold.yml`

For **apps-50>data**
 - `your_data.csv`

For **apps-50>replayer**
 - `Dockerfile`
 - `replay.py`
 - `requirement.txt`
 
For **apps-50>spark**
 - `consume_kafka.py`

For **secrets**
 - `wired-effort-483112-k2-59425ba2002c.json`

:::
Note that to circumvent "permission denied" issue, do not forget to authorization..for example:

::: callout-note
minkun@instance-20260311-173303:~$ sudo usermod -aG docker $USER  
# adds the current user to the docker group...to run Docker without typing sudo every time

minkun@instance-20260311-173303:~$ sudo chmod -R 777 30-airflow 
# makes the "30-airflow" folder fully accessible to everyone...but not good practice for security

minkun@instance-20260311-173303:~$ sudo chown -R minkun:minkun /home/minkun/  
# ensures files in that directory belong to user minkun

:::
Now establish connections between docker containers!

::: callout-note
minkun@instance-20260311-173303:~$ sudo usermod -aG docker $USER  

minkun@instance-20260311-173303:~$ newgrp docker 

minkun@instance-20260311-173303:~$ docker ps

minkun@instance-20260311-173303:~$ docker network create de_net 

:::
Then start docker containers

::: callout-note
minkun@instance-20260311-173303:~/10-kafka$ docker compose build

minkun@instance-20260311-173303:~/10-kafka$ docker compose down 

minkun@instance-20260311-173303:~/10-kafka$ `docker compose up -d` 

minkun@instance-20260311-173303:~/20-spark$ docker compose build 

minkun@instance-20260311-173303:~/20-spark$ docker compose down 

minkun@instance-20260311-173303:~/20-spark$ `docker compose up -d` 

minkun@instance-20260311-173303:~$ mkdir -p 30-airflow/{dags,logs,plugins,config} 

minkun@instance-20260311-173303:~/30-airflow$ docker compose up -d airflow-init 

minkun@instance-20260311-173303:~/30-airflow$ `docker compose up -d`  

minkun@instance-20260311-173303:~/30-airflow$ 
`docker ps --format "{{.Names}}" | grep '^30-airflow-' | while read name;` 
`do new_name=$(echo "$name" | sed 's/^30-airflow-//');` 
`docker rename "$name" "$new_name"; done` 

minkun@instance-20260311-173303:~/40-dbt$ docker compose build 

minkun@instance-20260311-173303:~/40-dbt$ docker compose down 

minkun@instance-20260311-173303:~/40-dbt$ `docker compose up -d` 

minkun@instance-20260311-173303:~/40-dbt$ `docker exec -it dbt-core bash` ##...DO NOT OVERWRITE

root@007ded5fb3b7:/usr/app# dbt init my_dbt_project 

root@007ded5fb3b7:/usr/app/my_dbt_project# dbt debug 

root@007ded5fb3b7:/usr/app/my_dbt_project# dbt docs generate 

root@007ded5fb3b7:/usr/app/my_dbt_project# `dbt docs serve --host 0.0.0.0 --port 7999`

root@007ded5fb3b7:/usr/app/my_dbt_project# 
`nohup dbt docs serve --host 0.0.0.0 -port 7999 > docs.log 2>&1 &` 

:::
Then, files, folders, etc. are created automatically, and we can open the web consoles:

- For kafka :::::: http://34.40.116.42:8080 
- For spark :::::: http://34.40.116.42:8081 
- For airflow :::::: http://34.40.116.42:8085 
- For dbt :::::: http://34.40.116.42:7999


#### (2) Ingestion (replayer sends events to Kafka in a loop, and Kafka sends to Spark )

::: callout-note
minkun@instance-20260311-173303:~/50-apps/replayer$ docker build -t kafka-replayer .

minkun@instance-20260311-173303:~/50-apps/replayer$  
`docker run --rm --network de_net -v $(pwd)/../data:/data kafka-replayer`

::: 
Next, let us consume the kafka message, using spark to store data points in a "parquet" format into GCS. For this, Go to GCP and create a bucket. Find "IAM" section, and find the "service accounts" on the left panel. Name "service-account-mk", and choose the permission as "editor". Access the "service-account-mk", move to the "key" tab to fetch the new JSON key and put it in the "secrets" folder in your machine. 

Now, submit spark job, using `consume_kafka.py`. 

::: callout-note
minkun@instance-20260311-173303:~/20-spark$   
`docker compose exec spark /opt/spark/bin/spark-submit \ --master local[*] \ --packages` `org.apache.spark:spark-sql-kafka-0` `10_2.12:3.5.1,com.google.cloud.bigdataoss:gcs-connector:hadoop3-2.2.19 \` `/opt/spark/work-dir/consume_kafka.py` 

:::

`consume_kafka.py`:

```{python}
#| code-fold: true
#| eval: false

####################################################################
# reads Kafka continuously
# writes to GCS as Parquet
# adds partition columns by processing time
# stays alive and prints a useful error if the stream fails
####################################################################

import time
from pyspark.sql import SparkSession
from pyspark.sql.functions import current_timestamp, date_format, col

# -----------------------------
# 1. Basic config
# -----------------------------
APP_NAME = "kafka-consumer"

BOOTSTRAP = "kafka:9092"
TOPIC = "signal_events"
GROUP_ID = "spark_signal_consumer"

GCS_PATH = "gs://test-kafka-mk/digiONS/raw"
GCS_CHECKPOINT = "gs://test-kafka-mk/checkpoints/digiONS"

GCP_KEYFILE = "/opt/spark/secrets/wired-effort-483112-k2-59425ba2002c.json"

# -----------------------------
# 2. SparkSession
# -----------------------------
spark = (
    SparkSession.builder
    .appName(APP_NAME)
    .config("spark.hadoop.fs.gs.impl", "com.google.cloud.hadoop.fs.gcs.GoogleHadoopFileSystem")
    .config("spark.hadoop.fs.AbstractFileSystem.gs.impl", "com.google.cloud.hadoop.fs.gcs.GoogleHadoopFS")
    .config("spark.hadoop.google.cloud.auth.service.account.enable", "true")
    .config("spark.hadoop.google.cloud.auth.service.account.json.keyfile", GCP_KEYFILE)
    .getOrCreate()
)

spark.sparkContext.setLogLevel("INFO")

print("Spark session created")
print("App name:", APP_NAME)
print("Kafka bootstrap:", BOOTSTRAP)
print("Kafka topic:", TOPIC)
print("GCS path:", GCS_PATH)
print("Checkpoint path:", GCS_CHECKPOINT)

# -----------------------------
# 3. Read Kafka stream
# -----------------------------
raw_df = (
    spark.readStream
    .format("kafka")
    .option("kafka.bootstrap.servers", BOOTSTRAP)
    .option("subscribe", TOPIC)
    .option("startingOffsets", "earliest")
    .option("kafka.group.id", GROUP_ID)
    .option("failOnDataLoss", "false")
    .load()
)

# Keep useful Kafka metadata too
value_df = raw_df.selectExpr(
    "CAST(key AS STRING) AS kafka_key",
    "CAST(value AS STRING) AS value",
    "topic",
    "partition",
    "offset",
    "timestamp AS kafka_timestamp"
)

# -----------------------------
# 4. Add processing-time partitions
# -----------------------------
with_ts = (
    value_df
    .withColumn("proc_ts", current_timestamp())
    .withColumn("event_date", date_format(col("proc_ts"), "yyyy-MM-dd"))
    .withColumn("event_hour", date_format(col("proc_ts"), "HH"))
    .withColumn("event_minute", date_format(col("proc_ts"), "mm"))
)

# -----------------------------
# 5. Write stream to GCS
# -----------------------------
query = (
    with_ts.writeStream
    .format("parquet")
    .option("path", GCS_PATH)
    .option("checkpointLocation", GCS_CHECKPOINT)
    .outputMode("append")
    .partitionBy("event_date", "event_hour", "event_minute")
    .queryName("signals_to_gcs_partitioned")
    .start()
)

print("Streaming query started")
print("Query name:", query.name)
print("Query id:", query.id)
print("Query runId:", query.runId)

# -----------------------------
# 6. Keep alive and show status
# -----------------------------
try:
    while query.isActive:
        print("----- stream status -----")
        print(query.status)
        if query.lastProgress is not None:
            print("Last progress:", query.lastProgress)
        else:
            print("Last progress: None yet")
        time.sleep(10)

    # If stream becomes inactive unexpectedly, surface the reason
    if query.exception() is not None:
        raise Exception(query.exception())

except KeyboardInterrupt:
    print("Stopping stream by user request...")
    query.stop()

except Exception as e:
    print("STREAM FAILED")
    print(str(e))
    raise

finally:
    print("Shutting down Spark session...")
    spark.stop()


```

![Figure 05. Google cloude storage bucket as a datalake. 
](images/GCS_datalake.png){width="600"}




### [C]. From Bronze to Silver Medallion

#### (1) Pick up your Bronze layer by creating BigQuery External Table

Let us identify the target GCS bucket first and the folder path that contains the Parquet files. Since Parquet is a self-describing format, BigQuery can infer the schema directly from the files, so an explicit schema definition is not strictly required. 

A table definition file can then be created with the `bq mkdef` command, and that definition is used to create the external table with `bq mk`. In this way, the raw data remain physically stored in GCS, while BigQuery provides SQL access to them as an external table.

Go to the GCP and "activate the cloud shell", and pick up the GCS bucket:

::: callout-note
minkun_kim4@cloudshell:~ (wired-effort-483112-k2)$ 

bq mkdef --source_format=PARQUET --hive_partitioning_mode=AUTO -- hive_partitioning_source_uri_prefix=gs://test-kafka-mk/digiONS/raw/ gs://test-kafka mk/digiONS/raw/event_date=* > digiONSsignal_ext.def 

::: 
And.. we create new dataset and table:

::: callout-note
minkun_kim4@cloudshell:~ (wired-effort-483112-k2)$ bq mk 
--dataset wired-effort-483112-k2:test 

minkun_kim4@cloudshell:~ (wired-effort-483112-k2)$ bq mk --external_table_definition=digiONSsignal_ext.def wired-effort-483112-k2:test.digiONSsignal_ext 

:::
Now, we can see the ``schema-on-read`` table!

![Figure 06. BigQuery External Table displayed via real-time query  
](images/medal03.png){width="800"}


#### (2) Silver layer and Silver validation test

From Silver, we need to parse this JSON, and give structure. 

![Figure 07. Parsing example  
](images/parse.png){width="800"}

Go back to VS Code, construct the Silver layer and perform the Silver test:

::: callout-note
minkun@instance-20260311-173303:~/40-dbt$ docker exec -it dbt-core bash

root@007ded5fb3b7:/usr/app/my_dbt_project# dbt debug 

root@007ded5fb3b7:/usr/app/my_dbt_project# dbt dep

root@007ded5fb3b7:/usr/app/my_dbt_project# dbt build 

:::

![Figure 08. dbt in action! Creating and testing the Silver layer. 
](images/build.png){width="600"}

During the execution, the eight data quality tests are subsequently performed on the standardized  dataset. The data points that violate one or more of these tests are consolidated into a summary table, which is materialized and made available for inspection in the GCP BigQuery console.

![Figure 09. Resulting tables of 8 DQ-tests. In the left-side panel, one can see that the Silver layer can be seen as successfully constructed.
](images/fail_table.png){width="800"}



### [D]. From Silver to Gold Medallion 

#### (1) Three Data Marts

In the Gold layer, the validated measurements (data points) from the Silver layer are aggregated and transformed into analysis-ready tables that can be queried directly without additional preprocessing. To implement this layer, three SQL models - `fct_signal_clean_15min.sql`,  `fct_signal_issue_daily.sql`, `fct_signal_quality_daily.sql`, and one YAML file - `gold.yml` are created and placed in the **gold** folder under the **models** directory of the **my_dbt_project**. 

 - **fct_signal_quality_daily** is a daily KPI monitoring table. It summarizes 15 minute signal intervals at the daily level. Under normal conditions, each day contains $24 × 4 = 96$ expected intervals. The table reports how many of these intervals are valid, empty, partial, and correctly aligned each day, thereby serving as a daily data quality monitoring dashboard. This allows the KPI related to timestamp alignment to be identified quickly on a daily basis. By showing whether 15-minute intervals are recorded at the correct quarter-hour timestamps, it provides a daily indication of whether DigiONS is functioning properly in terms of timestamp alignment.

 - **fct_signal_issue_daily** is a daily issue-type summary monitoring table. It summarizes row-level signal-quality issues by day. The issue includes (1) Incomplete 15-minute Window, (2) Missing Minute-level Signals, (3) Delayed Ingestion, (4) Other Collection Problem. For a substation monitoring context, this helps quickly see whether the problem is occasional or persistent, whether it clusters in certain days or periods, how long the problematic window lasted each day, etc. 

 - **fct_signal_clean_15min** is the clean analytical table for daily use. This table is not intended for monitoring; instead, it stores one trusted 15-minute substation interval per row after incomplete, null, misaligned, and internally inconsistent records have been removed. It is therefore suited to downstream analyses such as load-curve plotting, comparison of substation behavior over time, and other applications requiring reliable interval data. Accordingly, it preserves the original structure of the Power Exchange dataset while retaining only trusted records. 

To creat these data mart tables, use the following:

::: callout-note
root@5231af4ae491:/usr/app/my_dbt_project# `dbt run --select` `+ fct_signal_quality_daily +` `fct_signal_issue_daily + fct_signal_clean_15min` 

root@5231af4ae491:/usr/app/my_dbt_project# `dbt build` 

::: 
The resulting tables are shown in Figure 10. 

![Figure 10. Resulting three tables of the Gold layer.
](images/medal05.png){width="800"}




#### (2) Automating the Medallion pipeline

Now, we automate this pipeline across Bronze-Silver-Gold. Before we start, note the following:

::: callout-note
For **airflow-30>.dbt** 
 - `profiles.yml`
 - `.user.yml`
 
 
For **dbt-40>.dbt**
 - `profiles.yml`
 - `.user.yml`

::: 
Both folders contain YAML files with the same name. The former is used for automatic execution through Airflow, whereas the latter is intended for the manual execution workflow described so far. The following Figure 11. shows the different configurations of these two YAML files, despite sharing the same filename.


![Figure 11. YAML files for automatic and manual execution of the pipeline.
](images/profile.png){width="800"}

The following is our DAG files - `dbt_signal_layered.py` - to automate the pipeline execution. 

```{python}
#| code-fold: true
#| eval: false

from datetime import datetime
import subprocess
import pendulum

from airflow.sdk import dag, task
from airflow.operators.empty import EmptyOperator
from airflow.providers.slack.notifications.slack_webhook import send_slack_webhook_notification

GERMANY_TZ = pendulum.timezone("Europe/Berlin")

slack_fail_alert = send_slack_webhook_notification(
    slack_webhook_conn_id="slack_webhook",
    text=(
        ":red_circle: Airflow DAG failed.\n"
        "*DAG*: {{ dag.dag_id }}\n"
        "*Task*: {{ ti.task_id }}\n"
        "*Run ID*: {{ run_id }}\n"
        "*Logical Date*: {{ ds }}\n"
        "*Log URL*: {{ ti.log_url }}"
    ),
)

@dag(
    dag_id="dbt_signal_layered",
    start_date=datetime(2026, 3, 1, tzinfo=GERMANY_TZ),
    schedule="30 12 * * *",   # every day at 12:30 Europe/Berlin
    catchup=True,
    max_active_runs=3,
    tags=["dbt", "signal", "substation"],
    on_failure_callback=[slack_fail_alert],
)
def dbt_signal_layered():
    start = EmptyOperator(task_id="start")

    @task(task_id="run_bronze")
    def run_bronze():
        cmd = "cd /usr/app/my_dbt_project && dbt run --select tag:bronze"
        print(cmd)
        subprocess.run(cmd, check=True, shell=True)

    @task(task_id="run_silver")
    def run_silver():
        cmd = "cd /usr/app/my_dbt_project && dbt run --select tag:silver"
        print(cmd)
        subprocess.run(cmd, check=True, shell=True)

    @task(task_id="run_intermediate")
    def run_intermediate():
        cmd = "cd /usr/app/my_dbt_project && dbt run --select tag:intermediate"
        print(cmd)
        subprocess.run(cmd, check=True, shell=True)

    @task(task_id="run_gold")
    def run_gold():
        cmd = "cd /usr/app/my_dbt_project && dbt run --select tag:gold"
        print(cmd)
        subprocess.run(cmd, check=True, shell=True)

    @task(task_id="test_silver")
    def test_silver():
        cmd = "cd /usr/app/my_dbt_project && dbt test --select tag:silver"
        print(cmd)
        subprocess.run(cmd, check=True, shell=True)

    end = EmptyOperator(task_id="end")

    start >> run_bronze() >> run_silver() >> run_intermediate() >> run_gold() >> test_silver() >> end


dag = dbt_signal_layered()


```


::: callout-note
minkun@instance-20260311-173303:~/30-airflow$ 
`docker ps --format "table {{.Names}}\t{{.ID}}\t{{.Status}}"` 

minkun@instance-20260311-173303:~$ `docker exec -it airflow-dag-processor-1 bash`

airflow@97f2218af7c0:/opt/airflow$ airflow dags list | grep dbt_signal_layered

:::

Then go to http://34.40.116.42:8085 and we can perform:

![Figure 12. Airflow web console
](images/medal06.png){width="800"}


The following demonstration video clip illustrates the implemented workflow.

{{< video https://www.youtube.com/embed/EVqLe9Gzt70 >}}




<!--

## Bibliography
\[1\] Afroz, Python (2023). Power Exchange Data Germany. https://www.kaggle.com/datasets/
pythonafroz/power-exchange-data-germany. Accessed: 2026-01-27.

-->